# GeoNetwork
#
# Access via "http://localhost:8080/geonetwork" (or "http://$(docker-machine ip):8080/geonetwork" if using docker-machine)
#
# Default user: admin
# Default password: admin

version: '2'
services:

    geonetwork:
      image: geonetwork:3.0-postgres
      ports:
          - 8080:8080
      environment:
          DATA_DIR: /var/lib/geonetwork_data
          POSTGRES_DB_USERNAME: postgres
          POSTGRES_DB_PASSWORD: mysecretpassword
      volumes:
          - "/host/geonetwork-docker:/var/lib/geonetwork_data"
      links:
          - postgis:postgres
      depends_on:
          - postgis
    
    postgis:
      image: postgres:9.4
      ports:
          - 5432:5432
      volumes:
          - "/host/geonetwork-postgis:/var/lib/postgresql/data"
